// Code generated by Kitex v0.4.4. DO NOT EDIT.

package wechatservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	wechat "toktik/kitex_gen/douyin/wechat"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	WechatChat(ctx context.Context, Req *wechat.MessageChatRequest, callOptions ...callopt.Option) (r *wechat.MessageChatResponse, err error)
	WechatAction(ctx context.Context, Req *wechat.MessageActionRequest, callOptions ...callopt.Option) (r *wechat.MessageActionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kWechatServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kWechatServiceClient struct {
	*kClient
}

func (p *kWechatServiceClient) WechatChat(ctx context.Context, Req *wechat.MessageChatRequest, callOptions ...callopt.Option) (r *wechat.MessageChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.WechatChat(ctx, Req)
}

func (p *kWechatServiceClient) WechatAction(ctx context.Context, Req *wechat.MessageActionRequest, callOptions ...callopt.Option) (r *wechat.MessageActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.WechatAction(ctx, Req)
}
