apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    app: toktik-relation-api
  name: toktik-relation-api
  namespace: toktik-service-bundle
spec:
  selector:
    matchLabels:
      name: toktik-relation-api
  template:
    metadata:
      labels:
        app: toktik-relation-api
        branch: dev
        version: ${BUILD_NUMBER}-${CI_COMMIT_ID}
        name: toktik-relation-api
        dream-app: toktik-relation-api
        dream-unit: toktik-relation-api
    spec:
      volumes:
        - name: volume-storage
          persistentVolumeClaim:
            claimName: storage
      imagePullSecrets:
        - name: regcred
      containers:
        - image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          name: toktik-relation-api
          command:
            - /bin/bash
          args:
            - bootstrap-relation.sh
          envFrom:
            - configMapRef:
                name: env-config
            - configMapRef:
                name: config
          ports:
            - name: grpc-40133
              containerPort: 40133
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 8Mi
          volumeMounts:
            - name: volume-storage
              mountPath: /data/storage
      terminationGracePeriodSeconds: 30
