apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        sidecar.jaegertracing.io/inject: 'true'
    labels:
        app: toktik-auth-api
    name: toktik-auth-api
    namespace: toktik-service-bundle
spec:
    selector:
        matchLabels:
            name: toktik-auth-api
    template:
        metadata:
            labels:
                app: toktik-auth-api
                branch: dev
                version: ${BUILD_NUMBER}-${CI_COMMIT_ID}
                name: toktik-auth-api
                dream-app: toktik-auth-api
                dream-unit: toktik-auth-api
        spec:
            imagePullSecrets:
                -   name: regcred
            containers:
                -   image: ${IMAGE}
                    imagePullPolicy: IfNotPresent
                    name: toktik-auth-api
                    command:
                        - bin/auth
                    envFrom:
                        -   configMapRef:
                                name: env-config
                        -   configMapRef:
                                name: config
                    ports:
                        -   containerPort: 40127
            terminationGracePeriodSeconds: 30
