apiVersion: v1
kind: Service
metadata:
    labels:
        app: toktik-comment-api
    name: toktik-comment-api
    namespace: toktik-service-bundle
spec:
    ports:
        -   name: grpc
            port: 40131
            protocol: TCP
            targetPort: 40131
    selector:
        name: toktik-comment-api
        branch: dev
    type: ClusterIP
