name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "feat-github-action-unit-test" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build services into one image
        run: docker build . -f Dockerfile --tag toktik-srv:$(date +%s)
