name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "feat-github-action-unit-test" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build services into one image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: toktik-srv:$(date +%s)
          cache-from: type=gha
          cache-to: type=gha,mode=max
