name: Go Unit Tests

on: [push, pull_request]

env:
  GO111MODULE: "on"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          cache: true

      - name: Run Go Tests
        run: |
          for dir in service/*/; do
            pushd "$dir"
              go test -v -cover ./...
            popd
          done
